[package]
name = "weldify/containers"
description = "A collection of useful container implementations"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
